### PR TITLE
Be able to set monitor by absolute number #17

### PR DESCRIPTION
**Pull request by franckspike**
Added functions:
- Manager_activateMonitorAbs
- Manager_setViewMonitorAbs
- Manager_setWindowMonitorAbs
Modified Manager_loop to be more general

### CODE REVIEW

**Comment by joten** [comment]
I implemented the feature with commit 7d7c20f7161ac0b3b14cc53f3b62ac9d686068ca.

I also revised some more functions to ensure a consistent style for setting absolute and relative values, i. a. `Debug_setLogLevel`, `Manager_activateMonitor`, `Manager_setViewMonitor`, `Manager_setWindowMonitor`, `Monitor_activateView`, `Monitor_setWindowTag`, `View_setGapWidth`, `View_setLayout`, `View_setMFactor` and `View_shuffleWindow`.

Please see the documentation at https://github.com/fuhsjr00/bug.n/blob/master/doc/Default_hotkeys.md or the source code for more information on the specific implementation.

**Comment by joten** [comment]
By the way, thanks for the "more general Manager_loop". I adopted it with commit 64bccf01e5a47db473467657c5e4ea4fe9a04dce

**Comment by franckspike** [comment]
Hi,
I included a fix for Chrome's invisible window bug
and a server for remote commanding (from other AutoHotkey scripts as SendInput won't work on these).

I didn't want to make a pull request which is kind of tied to the previous I did...

**Comment by franckspike** [comment]
I know regexes are not pretty to read, but the remote commanding code is pretty to read :-)
I tried to look at PostMessage and OnMessage but I can't easily send a string through different processes. I could not find a better solution, maybe you have an idea ?

**Comment by joten** [comment]
What is it, you are using the remote control for?

**Comment by franckspike** [comment]
I have a gaming mouse with lots of buttons, but I use them as a programmer... that is I have an ahk script to do whatever I want with those "mouse keypresses", depending on the active and sloppy windows...  When I hover the bug.n bar, I want to change view, move windows, etc... So this remotecontrol gives me a kind of shell access to bug.n, I can call whatever functions I want from my other ahk script.

I tried to use Server.ahk as a library.. a plugin is require to be more dynamic than a library and couldn't get AutoHotkey to "maybe load" plugins and "maybe execute their init()"...

So I kept it inside bug.n and let Server_initialize() be called by Main.ahk as I didn't find any other more dynamic way to do it.

Note that AutoHotkey provides a IsFun() function, but it can't work with it.
The function is only auto included if we call it without using a "function pointer variable", and if it is not auto included then IsFunc will return false even if the function acually exists.
If we don't use a "function pointer variable" then a direct call to a function that doesn't exist causes a script error...

**Comment by joten** [comment]
I adopted the "remote control" code; most parts were already there, therefor an additional library was not necessary.

The variables are a bit different from your version, therefor please use the following syntax:
`ControlSetText, Edit2, % "<function name>(<comma separated list of arguments>)", bug.n_BAR_0`

If it is not working as expected, please open a new issue.

**Comment by franckspike** [comment]
Wow, that's so much cleaner!
We just need to pay attention not to have a , or ) inside a string argument.
It seems also that 

                        controlsettext, Edit2, % "Manager_activateMonitor(1)", bug.n_BAR_0
                        Sleep, 200
                        controlsettext, Edit2, % "Monitor_activateView(1)", bug.n_BAR_0

a Sleep is needed for a second command or the second text change event will not be received by the handler.

**Comment by franckspike** [comment]
I thought of maybe handling multiple lines of commands...

**Comment by joten** [comment]
> I thought of maybe handling multiple lines of commands...

Done.

> We just need to pay attention not to have a , or ) inside a string argument.

Right, but bug.n functions do comply.

> It seems also that a Sleep is needed for a second command or the second text change event will not be received by the handler.

I leave this to the external script, since I did not encounter any problems during my simple testing.

**Comment by franckspike** [comment]
Alright, I'll test it right away on my side

**Comment by franckspike** [comment]
Perfectly working! (And much more responsive without a sleep,200)

**Pull request closed without merging**
